UserLogin/UserLogin/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include
from basic_app import views
urlpatterns = [
    path('',views.index,name="index"),
    path('admin/', admin.site.urls),
    path('',include('basic_app.urls')),
    path('userlogout/',views.userlogout, name='logout'),
    path('special/',views.special, name='special'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UserLogin/basic_app/urls.py
from django.urls import path
from .import views

app_name='basic_app'


urlpatterns=[

            #path('',views.index,name='index'),
            path('basic_app/userlogin.html/',views.userlogin,name='userlogin'),
            path('basic_app/register.html/',views.register,name='register'),

]

UserLogin/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete="CASCADE_DELETE",related_name='profile')

    mobile =models.IntegerField(blank=True)

    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

UserLogin/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=('username','email','password')


class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model=UserProfileInfo
        fields=('mobile','profile_pic')      

UserLogin/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.





def index(request):

    return render(request,'basic_app/index.html',{})

def register(request):
    registered=False
    if request.method=="POST":
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()
            registered=True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()

    return render(request,'basic_app/register.html',{'user_form':user_form,
                                                    'profile_form':profile_form,
                                                    'registered':registered})

@login_required
def userlogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse('You are logged in Nice!')





def userlogin(request):
    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('Account Not Found!!!!!!!!')
        else:
            print("SomeOne tried to login but failed!")
            print("USername:{} and Password:{}".format(username,password))
    else:
        return render(request,'basic_app/userlogin.html',{})

UserLogin/basic_app/templates/basic_app/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'index' %}">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link " href="{% url 'basic_app:register' %}" tabindex="-1" aria-disabled="true">Register</a>
      </li>

      <li class="nav-item">
          {% if user.is_authenticated %}
           <img class="img-circle" src="{{ user.profile.profile_pic.url }}" width="50" height="50">
          <li><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a class="nav-link" href="{% url 'basic_app:userlogin' %}">Login</a></li>
          {% endif %}
      </li>

    </ul>
  </div>
</nav>

    {% block body_content %}



     {% endblock %}


  </body>
</html>

UserLogin/basic_app/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}


{% load static %}

<title>{% block title  %}Home {% endblock %} </title>

{% block body_content %}
      <div class="jumbotron">










      </div>
{% endblock %}

UserLogin/basic_app/templates/basic_app/register.html
{% extends 'basic_app/base.html' %}


{% load static %}

<title>{% block title  %}Register{% endblock %} </title>

{% block body_content %}
      <div class="jumbotron">
      {% if registered %}
      <h1>Thanks for registering!</h1>
      {% else %}
        <h1>Register Here!!</h1>
          <h3>Fill Out the form!!!!!</h3>

        <form enctype="multipart/form-data" method="post">
          {% csrf_token %}
           {{user_form.as_p}}
           {{profile_form.as_p}}
           <input type="submit" name="" value="Register">

        </form>
    {% endif %}

      </div>
{% endblock %}

UserLogin/basic_app/templates/basic_app/userlogin.html
{% extends 'basic_app/base.html' %}


{% load static %}

<title>{% block title  %} UserLogin {% endblock %} </title>

{% block body_content %}
      <div class="jumbotron">
       <h1>Please login!</h1>
       <form  action="{% url 'basic_app:userlogin' %}" method="post">
         {% csrf_token %}
         <label for="username">UserName:</label>
         <input type="text" name="username" placeholder="Enter Name">
          <label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">

          <input type="submit" name="" value="Login">

                  
       </form>









      </div>
{% endblock %}